title: "Tim's corner of the web"
description: "Here is an archive of all my thoughts, experience and journey."
baseurl: ""
url: "https://corner.timosahenru.space"
featured_image: "/assets/images/og-default.png"


# Build settings
markdown: kramdown
permalink: /note/:title/

# Custom variables
author: "Tim Osahenru"
social:
  github: "TimOsahenru"
  bluesky: "timosahenru.space"
  mastodon: "osahenru"

# Disable the default Minima CSS to avoid conflicts
minima:
  skin: none